[package]
name = "referendum_acceptance"
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = ">=2.18.0"

[[target.executable]]
name = "referendum_acceptance"
source-path = "src/main.cairo"
